# Generated by Django 5.2.1 on 2025-07-10 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='full_name',
            field=models.CharField(max_length=140, unique=True, verbose_name='Full Name'),
        ),
    ]
