# Generated by Django 5.2.1 on 2025-07-11 00:44

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_display_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='display_picture',
            field=models.FileField(blank=True, null=True, upload_to=accounts.models.upload_to),
        ),
    ]
