# Generated by Django 5.2.1 on 2025-07-10 16:30

import datetime
import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Hospitals',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField()),
                ('email', models.EmailField(max_length=120, unique=True)),
                ('location', models.CharField()),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', max_length=20)),
                ('phone', models.CharField(unique=True, validators=[django.core.validators.RegexValidator('^((([+](234){1}+(70|80|90|81))|(070|080|090|081))[0-9]{8})$', code='invalid_phone_no', message='Invalid Phone number entered!!')])),
                ('services', models.TextField(verbose_name='services')),
                ('accredition_license', models.CharField(default='null')),
                ('accredition_status', models.CharField(default='active')),
                ('accredition_expires', models.DateField(default=datetime.date.today)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('last_login', models.DateTimeField(auto_now=True)),
                ('plans', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hospitals', to='accounts.plans')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hospital', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Hospitals',
                'ordering': ['-date_joined'],
            },
        ),
    ]
