# Generated by Django 5.2.1 on 2025-07-03 17:52

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hospitals',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField()),
                ('email', models.EmailField(max_length=120, unique=True)),
                ('location', models.CharField()),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', max_length=20)),
                ('phone', models.CharField(unique=True, validators=[django.core.validators.RegexValidator('^((([+](234){1}+(70|80|90|81))|(070|080|090|081))[0-9]{8})$', code='invalid_phone_no', message='Invalid Phone number entered!!')])),
                ('services', models.TextField(default='unknown', verbose_name='services')),
                ('plans', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plans', to='accounts.plans')),
            ],
            options={
                'verbose_name_plural': 'Hospitals',
            },
        ),
    ]
