# Generated by Django 5.2.1 on 2025-07-03 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospitals', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hospitals',
            name='plans',
        ),
    ]
