# Generated by Django 5.2.1 on 2025-07-03 18:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('hospitals', '0002_remove_hospitals_plans'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospitals',
            name='plans',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='plans', to='accounts.plans'),
        ),
    ]
