# Generated by Django 5.2.1 on 2025-07-03 20:31

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('hospitals', '0003_hospitals_plans'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospitals',
            name='accredition_expires',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='hospitals',
            name='accredition_license',
            field=models.CharField(default='null'),
        ),
        migrations.AddField(
            model_name='hospitals',
            name='accredition_status',
            field=models.CharField(default='active'),
        ),
        migrations.AddField(
            model_name='hospitals',
            name='password',
            field=models.CharField(default='user2020'),
        ),
        migrations.AlterField(
            model_name='hospitals',
            name='plans',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hospitals', to='accounts.plans'),
        ),
        migrations.AlterField(
            model_name='hospitals',
            name='services',
            field=models.TextField(verbose_name='services'),
        ),
    ]
