# Generated by Django 5.2.1 on 2025-07-07 18:37

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitals', '0004_hospitals_accredition_expires_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospitals',
            name='date_joined',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hospitals',
            name='last_login',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='hospitals',
            name='password',
            field=models.CharField(),
        ),
    ]
