# Generated by Django 5.2.1 on 2025-07-07 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospitals', '0005_hospitals_date_joined_hospitals_last_login_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hospitals',
            options={'ordering': ['date_joined'], 'verbose_name_plural': 'Hospitals'},
        ),
    ]
