# Generated by Django 5.2.1 on 2025-07-07 22:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitals', '0006_alter_hospitals_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hospitals',
            options={'ordering': ['-date_joined'], 'verbose_name_plural': 'Hospitals'},
        ),
        migrations.RemoveField(
            model_name='hospitals',
            name='password',
        ),
        migrations.AddField(
            model_name='hospitals',
            name='display_picture',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/'),
        ),
        migrations.AddField(
            model_name='hospitals',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hospital', to=settings.AUTH_USER_MODEL),
        ),
    ]
