# Generated by Django 5.2.1 on 2025-07-08 11:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_plans_options'),
        ('hospitals', '0007_alter_hospitals_options_remove_hospitals_password_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospitals',
            name='plans',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hospitals', to='accounts.plans'),
        ),
    ]
